[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://mirror.rackspace.com/archlinux/core/os/x86_64

[extra]
Server = https://mirror.rackspace.com/archlinux/extra/os/x86_64

[chaotic-aur]
SigLevel = Optional TrustAll
Server = https://cdn-mirror.chaotic.cx/chaotic-aur/$arch

[arcolinux_repo]
SigLevel = Optional TrustAll
Server = https://arcolinux.github.io/$repo/$arch

[arcolinux_repo_3party]
SigLevel = Optional TrustAll
Server = https://arcolinux.github.io/$repo/$arch

# [endeavouros]
# SigLevel = Optional TrustAll
# Server = https://mirrors.tuna.tsinghua.edu.cn/endeavouros/repo/endeavouros/\$arch

[cachyos]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/\$arch/\$repo

[cachyos-v4]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64_v4/\$repo

[cachyos-core-v4]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64_v4/\$repo

[cachyos-extra-v4]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64_v4/\$repo