[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel = Never
LocalFileSigLevel = Never

[cachyos]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64/$repo

[cachyos-v4]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64_v4/$repo

[chaotic-aur]
SigLevel = Optional TrustAll
Server = https://cdn-mirror.chaotic.cx/chaotic-aur/$arch

[arcolinux_repo]
SigLevel = Optional TrustAll
Server = https://arcolinux.github.io/$repo/$arch

[core]
Server = https://mirror.rackspace.com/archlinux/core/os/x86_64

[extra]
Server = https://mirror.rackspace.com/archlinux/extra/os/x86_64