---
efiBootLoader: "systemd-boot" # Change from "grub" to "systemd-boot"

# This is the name that appears in your BIOS boot menu
bootloaderEntryName: "ZuccOS"

# Where to install the EFI files
installSearchPath: [ "/usr/bin/bootctl" ]

# This is critical for systemd-boot to find your kernel
kernel: "/vmlinuz-linux-cachyos-rt-bore"
img: "/initramfs-linux-cachyos-rt-bore.img"