backend: pacman

operations:
  - install:
    # CORE SYSTEM
    - base
    - linux-cachyos-rt-bore
    - linux-firmware
    - sudo
    - base-devel
    - networkmanager
    - grub
    - efibootmgr
    - nvidia-dkms
    - nvidia-utils
    - nvidia-settings
    
    # AUR & TOOLS
    - yay
    - git
    
    # OPENBOX DESKTOP
    - xorg-server
    - xorg-xinit
    - openbox
    - lightdm
    - lightdm-gtk-greeter
    - xterm
    - xf86-video-fbdev
    - tint2
    - nitrogen
    - obconf
    - lxappearance