---
modules-search: [ /usr/share/calamares/modules, local ]

instances:
- id:       packages
  module:   packages
  config:   packages.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users                # 1. Create the user first
  - networkcfg
  - packages@packages    # 2. Install kernel, Openbox, and Yay here
  - displaymanager       # 3. Setup LightDM (now that packages are there)
  - hwclock
  - services-systemd     # 4. Enable services
  - bootloader           # 6. Install Grub to the MBR/EFI partition
  - umount
- show:
  - finished

branding: default
prompt-install: true
dont-chroot: false
show-back-button: true
show-next-button: true
